# Generated by Django 5.1.2 on 2024-11-11 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_ingrid_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon_ingrid_api.procedure'),
            preserve_default=False,
        ),
    ]
