# Generated by Django 5.1.2 on 2024-11-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon_ingrid_api', '0004_alter_reservation_unique_together_reservation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='description',
        ),
    ]
